### ISSUE TITLE
请问如何适配各端的尺寸呢？

### ISSUE THREAD

**Issue by qiangxi** [bmfe/eros#97]
### 简略的描述你的问题。
这不是bug issue，只想求助，实在快被weex搞死了。。。
请问各位大佬该怎么适配尺寸呢？
```css
<style scoped>
    .concept-warpper {
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
        background-color: white;
        width: 750px;
        padding-top: 20px;
        padding-right: 20px;
        padding-bottom: 20px;
        padding-left: 20px;
        border-bottom-color: #eeeeee;
        border-bottom-width: 1px;
    }
    .text {
        color: #494949;
        font-size: 36px;
    }
</style>
```
比如上面的代码，有`padding`,`margin`,`width`,`height`,`fontsize`等，这些尺寸的单位都是px，但是px的适配极差，请问该怎么适配android&ios&web三个端呢？请大佬们帮帮忙，感谢！！
